"use client";

// ===========================================================================
// TEMPORARY PURCHASE PAUSE (added 2026-06-18 while switching payment providers).
// We cannot accept payments right now, so the booking form is disabled and a
// banner is shown site-wide.
//
// >>> TO RE-ENABLE PURCHASING: set PURCHASE_PAUSED to false below and redeploy.
//     That single change removes the banner, the form disclaimer, the gray-out
//     overlay and the popup on every page. Nothing else needs to be undone.
//     (Generated by content_engine/pause_purchasing.mjs - see
//      content_engine/docs/PURCHASE_PAUSE.md)
// ===========================================================================
import { useState } from "react";

export const PURCHASE_PAUSED = true;

export const PAUSE_MESSAGE =
  "We’re sorry for the inconvenience — we are not accepting new patients at this time, and online purchases are temporarily unavailable.";

// Full-width banner rendered at the very top of every page (from layout.tsx).
export function PauseBanner() {
  if (!PURCHASE_PAUSED) return null;
  return (
    <div
      role="alert"
      className="w-full bg-red-600 px-4 py-3 text-center text-sm font-medium leading-snug text-white sm:text-base"
    >
      {PAUSE_MESSAGE}
    </div>
  );
}

// Sits inside the booking form's root container. Shows the disclaimer at the top
// of the form, grays the entire form out, intercepts every click (so the user
// can never advance past step 1) and opens a popup with the same message.
// Renders nothing when PURCHASE_PAUSED is false (form behaves normally).
export function PurchasePauseGate() {
  const [showModal, setShowModal] = useState(false);
  if (!PURCHASE_PAUSED) return null;
  return (
    <>
      {/* Disclaimer pinned to the top of the form (kept bright above the overlay). */}
      <div className="relative z-30 mb-6 rounded-lg border border-amber-300 bg-amber-50 px-4 py-3 text-sm font-medium leading-snug text-amber-900">
        {PAUSE_MESSAGE}
      </div>

      {/* Gray-out overlay: dims the form, blocks all interaction and opens the
          popup on any click. Covers the whole relative form container. */}
      <button
        type="button"
        aria-label="Online purchases are temporarily unavailable"
        onClick={() => setShowModal(true)}
        className="absolute inset-0 z-20 h-full w-full cursor-not-allowed rounded-xl bg-gray-500/40 backdrop-blur-[1px]"
      />

      {/* Popup modal shown when the disabled form is clicked. */}
      {showModal && (
        <div
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/50 p-4"
          onClick={() => setShowModal(false)}
        >
          <div
            role="dialog"
            aria-modal="true"
            onClick={(e) => e.stopPropagation()}
            className="w-full max-w-md rounded-2xl bg-white p-6 text-center shadow-2xl"
          >
            <h2 className="text-lg font-bold text-gray-900">
              Purchases Temporarily Unavailable
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-gray-600">
              {PAUSE_MESSAGE}
            </p>
            <button
              type="button"
              onClick={() => setShowModal(false)}
              className="mt-6 inline-flex w-full items-center justify-center rounded-lg bg-red-600 px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-red-700"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </>
  );
}
